### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by karkkaz** [mcguffin/polylang-sync#35]
Hi, I noticed that this plugin is not yet compatible with PHP8 version, it causes error in Wordpress. Actually if the plugin is active the dashboard and admin area seems to work normally. But the update core page (/wp-admin/update-core.php) ends up in an error. I had to disable the plugin.

**Comment by mcguffin** [comment]
Auto-Updates are now handled through WPs `update_plugins_{$hostname}` filter. 
The issue should be fixed in 0.0.17.
